### ISSUE TITLE
More unique name?

### ISSUE THREAD

**Issue by bertob** [mrbenshef/Boop-GTK#81]
I'd suggest renaming to something more unique that doesn't include "GTK". Perhaps something like "Beep"?

I have a blog post on the subject you might be interested in: https://blogs.gnome.org/tbernard/2019/04/26/naming-your-app

**Comment by zoeyfyi** [comment]
Great article, will definitely refer back to this when starting another project! 

Funny enough, I was going to go with Beep, I choose Boop-GTK instead since I felt it was more important to express the fact that this is a cross platform port of Boop and perhaps it would go someways towards discoverability. I am not opposed to changing the name though it's considerably more difficult now that it's on the Snap store and Flathub.

**Comment by bertob** [comment]
That's fair, but having `-GTK` in the name is just not something modern apps do, so it doesn't fit in with the rest of the ecosystem. Personally I think renaming to something slightly different, e.g. "Beep" or "Bloop" would be an easy fix, keeping it familiar but getting rid of the weirdness.

FWIW changing the name doesn't necessarily mean you need to change the RDNN name (you can just keep that one and change the display name only) and I think Flathub actually allows migrating to a new RDNN nowadays.

**Comment by zoeyfyi** [comment]
I was following the discussion over [here](https://github.com/flathub/im.riot.Riot/issues/114) which raises a good reason for the app id and name to be the same. Unless its documented elsewhere, changing the app-id requires adding an EOL tag in the current flatpak repo and creating another. I am not sure the flatpak maintainers would appreciate an app EOL after a couple days :sweat_smile:.

I am going to leave this open because I do think "Beep", "Bloop" or maybe even "BeepBoop" are better names but prehaps as something to revisit later.

**Comment by Eonfge** [comment]
The app-id and the front-facing application name don't have to match. Better if they do, but if you want to change the name, then that's fine. (GNOME-) Videos is also called Totem underwater, and (GNOME-) Files is also still Nautilus underwater.

The choice is yours, but changing the name in the metainfo.xml is no trouble.

**Comment by zoeyfyi** [comment]
I am aware that the name on the desktop can be changed. Personally, I find it really annoying when the package name is not predictable and I have to go look it up. Also the reasons stated [here](https://github.com/flathub/im.riot.Riot/issues/114#issuecomment-659671203).

Having said that flatpak and snap do have search commands builtin.
